import { Metadata } from "next";
import "./globals.css";
import { Rambla } from "next/font/google";

const rambla = Rambla({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

import Providers from "./Provider";

export const metadata: Metadata = {
  title: "Movies App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      className="bg-background-backgroundDark"
      lang="PT-BR"
      suppressHydrationWarning
    >
      <body className={rambla.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
